global:
      message:Welcome to global microservices environment
logging:
  level:
    root:INFO
management:
  endpoints:
    web:
      exposure:
        inlude:health,info,refresh
endpoint:
  health:
    show-details:always
